#%RAML 0.8
title: saml-md-managment-api
version: v1
baseUri: http://www.jisc.ac.uk/saml-md-api/v1


/entities/{entityId}:
  description: Get a single entity resource. The EntityID must be URL encoded.
  get:
    description: Returns the SAML Metadata Descriptor relating to the EntityId if it exists.
    responses:
      404:
        description: Entity has not been found in the repository
        body:
          application/hal+xml:
            example: !include entityNotFound-404-error.xml

      401:
        description: No rights over entity {entityid}
      200:
        body:
          application/xml:
            example: !include getEntity-200-response.xml


  put:
    description: Updates the entity in full from the input entity.
    body:
      application/xml:
    responses:
      200:
        description: Entity updated


  delete:

/entities:
  description: List all entities
  get:
    responses:
      200:
        description: all entites returned
        body:
          application/json:
            example: |
              {}
      401:
        description: Not authorised to view any entities

  post:
    description: Adds a new entity fragment to the repository - subject to validation. Any validation errors are returned to the client.
    responses:
        200:
            body:
              application/json:
                example: |
                  {
                    "Result" : "Entity added"
                  }
        400:
            body:
                application/json:
                  example: |
                     {"ErrorStatus" : "Domain not owned by client member"}
